"""Add photo to complaints

Revision ID: 772f7d4a0df6
Revises: e6f7d5e01fdf
Create Date: 2026-07-23 15:10:37.198643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772f7d4a0df6'
down_revision: Union[str, Sequence[str], None] = 'e6f7d5e01fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'photo')
    # ### end Alembic commands ###
