"""add_transcript_english_to_complaints

Revision ID: e6f7d5e01fdf
Revises: 0992940c857d
Create Date: 2026-07-09 12:05:18.823597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f7d5e01fdf'
down_revision: Union[str, Sequence[str], None] = '0992940c857d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('transcript_english', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'transcript_english')
    # ### end Alembic commands ###
